<a href="https://colab.research.google.com/github/JishanAhmed2019/mba_561_data/blob/main/FinalProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Retail Transactions and Weather Data

**Data files:** `ities.parquet` (store transactions) and `max_temp.xz` (weekly high temperatures)

| Task | Points | What it asks for |
|---|---|---|
| 0 | 1 | Import the modules used in this document |
| 1 | 2 | Load `ities.parquet` into `dfi`; show info and first 5 rows |
| 2 | 2 | Load `max_temp.xz` into `dfw`; show info and first 5 rows |
| 3 | 4 | Convert datatypes, verify the conversions, explain the choices |

---
## Task 1 (1 point) - Import the modules

In [ ]:
# Task 1: imports
import pandas as pd
import numpy as np
import os

# Show all columns instead of collapsing the middle ones with "..."
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 200)

print("pandas version:", pd.__version__)
print("numpy version :", np.__version__)

pandas version: 2.2.3
numpy version : 2.1.3

## Setup: Load the Data from GitHub

The two data files are stored in a public GitHub repository, so there is no need to mount Google Drive or manage file permissions.

Cloning the repository copies the files directly into the current Colab session. This allows every group member to run the same code without changing file paths.

If this cell is run more than once in the same session, Git may display a harmless message indicating that the destination folder already exists.

In [ ]:
if not os.path.exists("/content/mba_561_data"):
    !git clone -q https://github.com/JishanAhmed2019/mba_561_data.git

DATA_DIR = "/content/mba_561_data/"
print("Files found:", os.listdir(DATA_DIR))

Files found: ['ities.parquet', 'max_temp.xz', '.git']

---
## Task 2 (2 points) - Load `ities.parquet` into `dfi`

Parquet stores the column names and types inside the file, so `read_parquet` needs nothing but the path.

In [ ]:
# Task 2: load the transaction data
dfi = pd.read_parquet(DATA_DIR + "ities.parquet")

dfi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438151 entries, 0 to 438150
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Date               438151 non-null  object
 1   OperationType      438151 non-null  object
 2   CashierName        438151 non-null  object
 3   LineItem           438151 non-null  object
 4   Department         438151 non-null  object
 5   Category           438151 non-null  object
 6   RegisterName       438151 non-null  object
 7   StoreNumber        438151 non-null  object
 8   TransactionNumber  438151 non-null  object
 9   CustomerCode       438151 non-null  object
 10  Price              438139 non-null  float64
 11  Quantity           438151 non-null  int64
 12  TotalDue           438139 non-null  float64
dtypes: float64(2), int64(1), object(10)
memory usage: 43.5+ MB

In [ ]:
dfi.head(5)

        Date OperationType     CashierName                     LineItem Department                     Category RegisterName StoreNumber TransactionNumber CustomerCode  Price  Quantity  TotalDue
0  7/18/2016          SALE  Wallace Kuiper  Salmon and Wheat Bran Salad    Entrees  Salmon and Wheat Bran Salad        RT149  AZ23501305     002XIIC146121  CWM11331L8O  66.22         1     66.22
1  7/18/2016          SALE  Wallace Kuiper               Fountain Drink   Beverage                     Fountain        RT149  AZ23501289     002XIIC146121  CWM11331L8O   2.88         1      2.88
2  7/18/2016          SALE  Wallace Kuiper        Beef and Squash Kabob     Kabobs                         Beef        RT149  AZ23501367     00PG9FL135736  CWM11331L8O  12.02         2     24.04
3  7/18/2016          SALE  Wallace Kuiper  Salmon and Wheat Bran Salad      Salad                      general        RT149  AZ23501633      00Z3B4R37335  CWM11331L8O  18.43         1     18.43
4  7/18/2016          SALE  Wallace Kuiper  Salmon and Wheat Bran Salad      Salad                      general        RT149  AZ23501633      00Z3B4R37335  CWM11331L8O  18.43         1     18.43

---
## Task 3 (2 points) - Load `max_temp.xz` into `dfw`

This file is a pandas DataFrame that was pickled and then compressed with xz. `read_pickle` handles both
steps at once — it sees the `.xz` extension and decompresses automatically.

In [ ]:
# Task 3: load the weather data
dfw = pd.read_pickle(DATA_DIR + "max_temp.xz")

dfw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Week          52 non-null     int64
 1   Monday        52 non-null     float64
 2   Tuesday       52 non-null     float64
 3   Wednesday     52 non-null     float64
 4   Thursday      52 non-null     float64
 5   Friday        52 non-null     float64
 6   Saturday      52 non-null     float64
 7   Sunday        52 non-null     float64
 8   WeekStarting  52 non-null     object
dtypes: float64(7), int64(1), object(1)
memory usage: 3.8+ KB

In [ ]:
dfw.head(5)

   Week  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday  Sunday WeekStarting
0     1   46.94    44.96      41.00     44.96   59.00     57.02   57.02     1/3/2016
1     2   48.92    46.04      46.04     46.94   51.08     42.08   48.92    1/10/2016
2     3   48.02    51.98      53.06     55.04   50.00     51.08   50.00    1/17/2016
3     4   33.98    41.00      51.08     46.94   55.94     51.08   35.96    1/24/2016
4     5   51.08    60.08      57.92     51.08   41.00     48.02   51.98    1/31/2016

## Task 4 (4 points) - Make necessary datatype conversions

The `Date` column in `dfi` and the `WeekStarting` column in `dfw` contain dates but initially load as `object`. Both should be converted to pandas datetime values.

In [ ]:
# Convert date columns to datetime
dfi["Date"] = pd.to_datetime(dfi["Date"]).dt.normalize()
dfw["WeekStarting"] = pd.to_datetime(dfw["WeekStarting"]).dt.normalize()

# Verify the conversions
print("Updated information for dfi:")
dfi.info()

print("\nUpdated information for dfw:")
dfw.info()

Updated information for dfi:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438151 entries, 0 to 438150
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Date               438151 non-null  datetime64[ns]
 1   OperationType      438151 non-null  object
 2   CashierName        438151 non-null  object
 3   LineItem           438151 non-null  object
 4   Department         438151 non-null  object
 5   Category           438151 non-null  object
 6   RegisterName       438151 non-null  object
 7   StoreNumber        438151 non-null  object
 8   TransactionNumber  438151 non-null  object
 9   CustomerCode       438151 non-null  object
 10  Price              438139 non-null  float64
 11  Quantity           438151 non-null  int64
 12  TotalDue           438139 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(9)
memory usage: 43.5+ MB

Updated information for dfw:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Week          52 non-null     int64
 1   Monday        52 non-null     float64
 2   Tuesday       52 non-null     float64
 3   Wednesday     52 non-null     float64
 4   Thursday      52 non-null     float64
 5   Friday        52 non-null     float64
 6   Saturday      52 non-null     float64
 7   Sunday        52 non-null     float64
 8   WeekStarting  52 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(7), int64(1)
memory usage: 3.8 KB

In [ ]:
# Check that the date conversions really worked

# If any date failed to parse it becomes NaT, so this count should be 0.
print("Bad dates in dfi:", dfi["Date"].isna().sum())
print("Bad dates in dfw:", dfw["WeekStarting"].isna().sum())

# Date math is now possible, which was the whole point.
print("\ndfi date range:", dfi["Date"].min(), "to", dfi["Date"].max())
print("dfw date range:", dfw["WeekStarting"].min(), "to", dfw["WeekStarting"].max())

print("\nTransactions by day of week:")
print(dfi["Date"].dt.day_name().value_counts())

# Every WeekStarting should land on the same weekday.
print("\nWeekStarting always falls on:", dfw["WeekStarting"].dt.day_name().unique())

Bad dates in dfi: 0
Bad dates in dfw: 0

dfi date range: 2014-01-04 00:00:00 to 2017-04-05 00:00:00
dfw date range: 2016-01-03 00:00:00 to 2016-12-25 00:00:00

Transactions by day of week:
Date
Saturday     94482
Friday       94327
Thursday     69358
Wednesday    66523
Tuesday      58998
Monday       54442
Sunday          21
Name: count, dtype: int64

WeekStarting always falls on: ['Sunday']

### Why I made these datatype conversions

I converted `dfi["Date"]` and `dfw["WeekStarting"]` from `object` to `datetime64[ns]`. These columns contain dates, so storing them as datetime values is more appropriate than storing them as text. This conversion is also important for later tasks because I need to aggregate sales by date, add days to `WeekStarting`, sort chronologically, and join the two DataFrames using dates. The updated dataframe information confirms that both columns are now stored as datetime values.

I left the other columns unchanged because their existing datatypes are appropriate. `Price` and `TotalDue` are numeric measurements stored as `float64`, while `Quantity` and `Week` are whole numbers stored as `int64`. The daily temperature columns are already numeric (`float64`). Columns such as `StoreNumber`, `TransactionNumber`, and `CustomerCode` are identifiers rather than numerical measurements, so keeping them as text is appropriate. The remaining object columns contain names or categories and do not require conversion for the tasks in this analysis.

In [ ]:
dfi.head()

        Date OperationType     CashierName                     LineItem Department                     Category RegisterName StoreNumber TransactionNumber CustomerCode  Price  Quantity  TotalDue
0 2016-07-18          SALE  Wallace Kuiper  Salmon and Wheat Bran Salad    Entrees  Salmon and Wheat Bran Salad        RT149  AZ23501305     002XIIC146121  CWM11331L8O  66.22         1     66.22
1 2016-07-18          SALE  Wallace Kuiper               Fountain Drink   Beverage                     Fountain        RT149  AZ23501289     002XIIC146121  CWM11331L8O   2.88         1      2.88
2 2016-07-18          SALE  Wallace Kuiper        Beef and Squash Kabob     Kabobs                         Beef        RT149  AZ23501367     00PG9FL135736  CWM11331L8O  12.02         2     24.04
3 2016-07-18          SALE  Wallace Kuiper  Salmon and Wheat Bran Salad      Salad                      general        RT149  AZ23501633      00Z3B4R37335  CWM11331L8O  18.43         1     18.43
4 2016-07-18          SALE  Wallace Kuiper  Salmon and Wheat Bran Salad      Salad                      general        RT149  AZ23501633      00Z3B4R37335  CWM11331L8O  18.43         1     18.43

In [ ]:
dfw.head()

   Week  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday  Sunday WeekStarting
0     1   46.94    44.96      41.00     44.96   59.00     57.02   57.02   2016-01-03
1     2   48.92    46.04      46.04     46.94   51.08     42.08   48.92   2016-01-10
2     3   48.02    51.98      53.06     55.04   50.00     51.08   50.00   2016-01-17
3     4   33.98    41.00      51.08     46.94   55.94     51.08   35.96   2016-01-24
4     5   51.08    60.08      57.92     51.08   41.00     48.02   51.98   2016-01-31